services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
     image: mysql:5.7
     volumes:
       - ./database/data:/var/lib/mysql
       - ./database/initdb.d:/docker-entrypoint-initdb.d
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: sdshdb
       MYSQL_USER: sdshuser
       MYSQL_PASSWORD: asjdhfgasdf7saddgahafg56
     networks:
       - wpsite

  # phpmyadmin
  phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - '8080:80'
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: password
     networks:
       - wpsite

  wordpress:
     image: wordpress:latest
     ports:
       - 8000:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: sdshuser
       WORDPRESS_DB_PASSWORD: asjdhfgasdf7saddgahafg56
       WORDPRESS_DB_NAME: sdshdb
     volumes:
       - ./src:/var/www/html
     networks:
       - wpsite

networks:
    wpsite:

volumes:
    db_data: {}
