services:
  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 8000:80
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - wordpress_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: wordpress_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite 

  wordpress_db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sdshdb
      MYSQL_USER: sdshuser
      MYSQL_PASSWORD: asjdhfgasdf7saddgahafg56
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data:

