services:

  wordpress_db:
    image: mariadb
    container_name: wordpress_db
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbs9334747
      MYSQL_USER: dbu1703375
      MYSQL_PASSWORD: '%ZDVyr0/ertR'

  wordpress:
    depends_on:
    - wordpress_db
    image: wordpress:php7.1 # we're using the image with php7.1 
    container_name: wordpress
    ports:
      - "8000:80"
    restart: always
    links:
    - wordpress_db:mysql
    volumes:
    - ./src:/var/www/html
