services:
  wordpress:
    image: wordpress
    links:
      - wordpress_db:mysql
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: dbu1703375
      WORDPRESS_DB_PASSWORD: asjdhfgasdf7saddgahafg56
      WORDPRESS_DB_NAME: sdshdb
    volumes:
      - ./src:/var/www/html
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - wordpress_db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: wordpress_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite 

  wordpress_db:
    image: mariadb
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbs9334747
      MYSQL_USER: dbu1703375
      MYSQL_PASSWORD: '%ZDVyr0/ertR'
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data:


